<a href="https://colab.research.google.com/github/Kaleab1999/Ethiopia-airlines-tweeter-review-sentiment-analysis/blob/main/tfidf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

import numpy as np
import re
import string
import spacy


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df= pd.read_csv('/content/drive/MyDrive/dataset/merge-csv.com__6361876ee50a8.csv', encoding='unicode_escape')
df.head()

created_at       user_id              name     label  \
0  2022-10-28 23:15:24 UTC  4.386524e+08       AfricanSon®  negative   
1  2022-10-28 22:53:28 UTC  1.320000e+18      Bargo YOUSIF  negative   
2  2022-10-28 22:21:31 UTC  8.226798e+08  Dr. Aklog Birara  positive   
3  2022-10-28 19:46:19 UTC  1.470000e+18              bill  negative   
4  2022-10-28 16:40:48 UTC  1.570000e+18          OverMeon   neutral   

                                               tweet language  \
0  Ethiopian Airlines (EA) flight ET-3717 was int...       en   
1  _ details: It's #Ethiopian_Airlines flight, sm...       en   
2  I look forward to seeing integrated infrastruc...       en   
3  @jaeyoonieee me getting on ethiopian airlines ...       en   
4  #ETH552 ET-AVE A350 941 Ethiopian Airlines ADD...       en   

                                                link  Column1  
0  https://twitter.com/samsenge/status/1586134568...      NaN  
1  https://twitter.com/BargoYousif/status/1586129...      NaN  
2  https://twitter.com/DrAklogBirara/status/15861...      NaN  
3  https://twitter.com/ysfkd_/status/158608195096...      NaN  
4  https://twitter.com/OverMeon/status/1586035262...      NaN

In [4]:
df['length']= df['tweet'].apply(lambda x: len(x.split()))

df.head()

created_at       user_id              name     label  \
0  2022-10-28 23:15:24 UTC  4.386524e+08       AfricanSon®  negative   
1  2022-10-28 22:53:28 UTC  1.320000e+18      Bargo YOUSIF  negative   
2  2022-10-28 22:21:31 UTC  8.226798e+08  Dr. Aklog Birara  positive   
3  2022-10-28 19:46:19 UTC  1.470000e+18              bill  negative   
4  2022-10-28 16:40:48 UTC  1.570000e+18          OverMeon   neutral   

                                               tweet language  \
0  Ethiopian Airlines (EA) flight ET-3717 was int...       en   
1  _ details: It's #Ethiopian_Airlines flight, sm...       en   
2  I look forward to seeing integrated infrastruc...       en   
3  @jaeyoonieee me getting on ethiopian airlines ...       en   
4  #ETH552 ET-AVE A350 941 Ethiopian Airlines ADD...       en   

                                                link  Column1  length  
0  https://twitter.com/samsenge/status/1586134568...      NaN      31  
1  https://twitter.com/BargoYousif/status/1586129...      NaN      31  
2  https://twitter.com/DrAklogBirara/status/15861...      NaN      33  
3  https://twitter.com/ysfkd_/status/158608195096...      NaN      12  
4  https://twitter.com/OverMeon/status/1586035262...      NaN      36

In [5]:
df['length'].max()

64

In [6]:
!pip install text-hammer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 115 kB 5.1 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [7]:
import text_hammer as th

/usr/local/lib/python3.7/dist-packages/spacy/language.py:1899: UserWarning: [W123] Argument disable with value [] is used instead of ['senter'] as specified in the config. Be aware that this might affect other components in your pipeline.
  config_value=config["nlp"][key],


In [8]:
nlp= spacy.load('en_core_web_sm')

In [9]:
def preprocessor(x):
  doc= nlp(x)

  text= [word.lemma_.lower().strip() for word in doc ]
  text = str(x).lower().replace('\\', '').replace('_', ' ')
  text = th.cont_exp(text)
  text = th.remove_emails(text)
  text = th.remove_urls(text)
  text = th.remove_html_tags(text)
  text = th.remove_rt(text)
  text = th.remove_accented_chars(text)
  text = th.remove_special_chars(text)
  text = re.sub("(.)\\1{2,}", "\\1", text)

  return text

In [10]:
df['tokenized']=  df['tweet'].apply(preprocessor)

In [11]:
df['encode']= df['label'].astype('category').cat.codes

In [12]:
df.head()

created_at       user_id              name     label  \
0  2022-10-28 23:15:24 UTC  4.386524e+08       AfricanSon®  negative   
1  2022-10-28 22:53:28 UTC  1.320000e+18      Bargo YOUSIF  negative   
2  2022-10-28 22:21:31 UTC  8.226798e+08  Dr. Aklog Birara  positive   
3  2022-10-28 19:46:19 UTC  1.470000e+18              bill  negative   
4  2022-10-28 16:40:48 UTC  1.570000e+18          OverMeon   neutral   

                                               tweet language  \
0  Ethiopian Airlines (EA) flight ET-3717 was int...       en   
1  _ details: It's #Ethiopian_Airlines flight, sm...       en   
2  I look forward to seeing integrated infrastruc...       en   
3  @jaeyoonieee me getting on ethiopian airlines ...       en   
4  #ETH552 ET-AVE A350 941 Ethiopian Airlines ADD...       en   

                                                link  Column1  length  \
0  https://twitter.com/samsenge/status/1586134568...      NaN      31   
1  https://twitter.com/BargoYousif/status/1586129...      NaN      31   
2  https://twitter.com/DrAklogBirara/status/15861...      NaN      33   
3  https://twitter.com/ysfkd_/status/158608195096...      NaN      12   
4  https://twitter.com/OverMeon/status/1586035262...      NaN      36   

                                           tokenized  encode  
0  ethiopian airlines ea flight et3717 was interc...       0  
1  details it is ethiopian airlines flight smoke ...       0  
2  i look forward to seeing integrated infrastruc...       2  
3  jaeyoonie me getting on ethiopian airlines and...       0  
4  eth552 etavenuea350 941 ethiopian airlines adu...       1

In [13]:
df['label'].value_counts()

neutral     2274
positive    1119
negative    1036
Name: label, dtype: int64

In [14]:
corpus= list(df['tokenized'])

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf= TfidfVectorizer(max_features=10000, ngram_range=(2,2))

X=tf.fit_transform(corpus)

In [16]:
y= df['encode'].tolist()

In [17]:
from imblearn.over_sampling import SMOTE
over= SMOTE()

X,y = over.fit_resample(X,y)

In [18]:
len(y)

6822

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_text, y_train, y_test= train_test_split(X, y, test_size=0.2, stratify= y)

In [20]:
len(y_train)

5457

In [21]:

X_train = X_train.toarray()

In [22]:
X_text= X_text.toarray()

In [23]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

pred= gnb.predict(X_text)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,pred)
print(matrix)
score=accuracy_score(y_test,pred)
print(score)
report=classification_report(y_test,pred)
print(report)

[[435   4  16]
 [ 51 316  88]
 [ 22  23 410]]
0.8505494505494505
              precision    recall  f1-score   support

           0       0.86      0.96      0.90       455
           1       0.92      0.69      0.79       455
           2       0.80      0.90      0.85       455

    accuracy                           0.85      1365
   macro avg       0.86      0.85      0.85      1365
weighted avg       0.86      0.85      0.85      1365



In [24]:
from sklearn.linear_model import LogisticRegression

lr= LogisticRegression()

lr.fit(X_train, y_train)

predi= lr.predict(X_text)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,predi)
print(matrix)
score=accuracy_score(y_test,predi)
print(score)
report=classification_report(y_test,predi)
print(report)


[[403  12  40]
 [ 29 344  82]
 [ 15  26 414]]
0.8505494505494505
              precision    recall  f1-score   support

           0       0.90      0.89      0.89       455
           1       0.90      0.76      0.82       455
           2       0.77      0.91      0.84       455

    accuracy                           0.85      1365
   macro avg       0.86      0.85      0.85      1365
weighted avg       0.86      0.85      0.85      1365



In [30]:
from sklearn.ensemble import RandomForestClassifier
randomclassifier=RandomForestClassifier(n_estimators=80, criterion='entropy')
randomclassifier.fit(X_train,y_train)

pred= randomclassifier.predict(X_text)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,pred)
print(matrix)
score=accuracy_score(y_test,pred)
print(score)
report=classification_report(y_test,pred)
print(report)

[[383  33  39]
 [ 15 371  69]
 [ 10  69 376]]
0.8278388278388278
              precision    recall  f1-score   support

           0       0.94      0.84      0.89       455
           1       0.78      0.82      0.80       455
           2       0.78      0.83      0.80       455

    accuracy                           0.83      1365
   macro avg       0.83      0.83      0.83      1365
weighted avg       0.83      0.83      0.83      1365

[[381  29  45]
 [ 13 374  68]
 [  7  70 378]]
0.8300366300366301
              precision    recall  f1-score   support

           0       0.95      0.84      0.89       455
           1       0.79      0.82      0.81       455
           2       0.77      0.83      0.80       455

    accuracy                           0.83      1365
   macro avg       0.84      0.83      0.83      1365
weighted avg       0.84      0.83      0.83      1365



In [26]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(X_train, y_train)  

pred= classifier.predict(X_text)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,pred)
print(matrix)
score=accuracy_score(y_test,pred)
print(score)
report=classification_report(y_test,pred)
print(report)

[[406  13  36]
 [ 29 342  84]
 [ 17  28 410]]
0.8483516483516483
              precision    recall  f1-score   support

           0       0.90      0.89      0.90       455
           1       0.89      0.75      0.82       455
           2       0.77      0.90      0.83       455

    accuracy                           0.85      1365
   macro avg       0.85      0.85      0.85      1365
weighted avg       0.85      0.85      0.85      1365

