<a href="https://colab.research.google.com/github/Kaleab1999/Ethiopia-airlines-tweeter-review-sentiment-analysis/blob/main/thesis1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install text-hammer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 115 kB 4.4 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import text_hammer as th
import spacy
import string
import re

/usr/local/lib/python3.7/dist-packages/spacy/language.py:1899: UserWarning: [W123] Argument disable with value [] is used instead of ['senter'] as specified in the config. Be aware that this might affect other components in your pipeline.
  config_value=config["nlp"][key],


In [4]:
df= pd.read_csv('/content/drive/MyDrive/dataset/merge-csv.com__6361876ee50a8.csv' , encoding= 'unicode_escape')
df.head()

created_at       user_id              name     label  \
0  2022-10-28 23:15:24 UTC  4.386524e+08       AfricanSon®  negative   
1  2022-10-28 22:53:28 UTC  1.320000e+18      Bargo YOUSIF  negative   
2  2022-10-28 22:21:31 UTC  8.226798e+08  Dr. Aklog Birara  positive   
3  2022-10-28 19:46:19 UTC  1.470000e+18              bill  negative   
4  2022-10-28 16:40:48 UTC  1.570000e+18          OverMeon   neutral   

                                               tweet language  \
0  Ethiopian Airlines (EA) flight ET-3717 was int...       en   
1  _ details: It's #Ethiopian_Airlines flight, sm...       en   
2  I look forward to seeing integrated infrastruc...       en   
3  @jaeyoonieee me getting on ethiopian airlines ...       en   
4  #ETH552 ET-AVE A350 941 Ethiopian Airlines ADD...       en   

                                                link  Column1  
0  https://twitter.com/samsenge/status/1586134568...      NaN  
1  https://twitter.com/BargoYousif/status/1586129...      NaN  
2  https://twitter.com/DrAklogBirara/status/15861...      NaN  
3  https://twitter.com/ysfkd_/status/158608195096...      NaN  
4  https://twitter.com/OverMeon/status/1586035262...      NaN

In [5]:
df.shape

(4429, 8)

In [6]:
y= df.iloc[:, 1]
y.head()

0    4.386524e+08
1    1.320000e+18
2    8.226798e+08
3    1.470000e+18
4    1.570000e+18
Name: user_id, dtype: float64

In [7]:
nlp= spacy.load('en_core_web_sm')

stopwords= nlp.Defaults.stop_words
print(stopwords)

{'rather', 'because', 'please', 'forty', 'nobody', 'another', 'never', 'here', 'make', 'say', 'again', 'either', 'it', 'both', 'who', 'off', 'whence', 'keep', 'became', 'six', 'n’t', 'do', 'did', 'made', 'almost', 'thence', 'well', 'other', 'would', 'per', 'anyhow', 'himself', 'twenty', 'had', 'whenever', 'too', 'all', 'yours', 'at', 'they', 'enough', 'she', 'on', 'the', 'some', 'may', 'yourself', 'from', 'is', 'serious', '‘ll', 'becomes', 'our', 'being', 'when', '‘ve', 'hereafter', 'due', 'no', 'thereby', 'below', 'eight', 'that', 'he', 'everything', 'with', 'hers', "'ll", 'three', 'in', 'myself', 'even', 'me', 'toward', 'each', 'cannot', 'side', 'why', 'her', 'various', 'move', 'wherein', 'least', 'to', 'whereby', 'same', 'his', 'sixty', 'back', 'onto', 'beyond', 'indeed', 'anyway', 'doing', 'somehow', "'re", 'something', 'put', 'under', 'after', 'a', 'am', 'nor', 'hence', 'own', 'can', 'beforehand', 'was', 'amongst', 'together', 'herein', '’ve', 'whoever', 'less', 'namely', 'into', 

In [8]:
def text_preprocessor(x):

  doc = nlp(x)
  
  text= [word.lemma_.lower().strip() for word in doc ]
  text = str(x).lower().replace('\\', '').replace('_', ' ')
  text = th.cont_exp(text)
  text = th.remove_emails(text)
  text = th.remove_urls(text)
  text = th.remove_html_tags(text)
  text = th.remove_rt(text)
  text = th.remove_accented_chars(text)
  text = th.remove_special_chars(text)
  text = re.sub("(.)\\1{2,}", "\\1", text)

  



  return text

  


In [9]:
df['processed']= df['tweet'].apply(text_preprocessor)
df[['processed','tweet']].head()

processed  \
0  ethiopian airlines ea flight et3717 was interc...   
1  details it is ethiopian airlines flight smoke ...   
2  i look forward to seeing integrated infrastruc...   
3  jaeyoonie me getting on ethiopian airlines and...   
4  eth552 etavenuea350 941 ethiopian airlines adu...   

                                               tweet  
0  Ethiopian Airlines (EA) flight ET-3717 was int...  
1  _ details: It's #Ethiopian_Airlines flight, sm...  
2  I look forward to seeing integrated infrastruc...  
3  @jaeyoonieee me getting on ethiopian airlines ...  
4  #ETH552 ET-AVE A350 941 Ethiopian Airlines ADD...

In [10]:
from gensim.models import word2vec
from gensim.models.word2vec import Word2Vec
import gensim.downloader as api

In [11]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 2.4 MB/s 
     |████████████████████████████████| 5.5 MB 9.2 MB/s 
     |████████████████████████████████| 1.3 MB 39.6 MB/s 
     |████████████████████████████████| 163 kB 35.3 MB/s 
     |████████████████████████████████| 7.6 MB 35.2 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=9e3d9083cd7874853632d7f9f71664921ac6fb75f697ce418453f1f1f6d551e8
  Stored in directory: /root/.cache/pip/wheels/bf/06/fb/d59c1e5bd1dac7f6cf61ec0036cc3a10ab8fecaa6b2c3d3ee9
Successfully built sentence-transformers


In [12]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

df['vector']= df['processed'].apply(model.encode)

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/612 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/350 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [13]:
df[['processed','vector', 'label']].head()

processed  \
0  ethiopian airlines ea flight et3717 was interc...   
1  details it is ethiopian airlines flight smoke ...   
2  i look forward to seeing integrated infrastruc...   
3  jaeyoonie me getting on ethiopian airlines and...   
4  eth552 etavenuea350 941 ethiopian airlines adu...   

                                              vector     label  
0  [-0.02903445, 0.022428248, -0.05338361, 0.0497...  negative  
1  [-0.0039975177, 0.10077321, -0.028292205, 0.06...  negative  
2  [-0.02492736, 0.04924348, -0.014382833, 0.0545...  positive  
3  [0.0296782, 0.117856614, 0.015417021, 0.026076...  negative  
4  [0.03090392, 0.03790238, -0.057798278, 0.00320...   neutral

In [14]:
import gensim.downloader as api
import numpy as np
from gensim.models import word2vec
from gensim.models.word2vec import Word2Vec
import spacy
import string

In [15]:
wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [16]:
import numpy as np
def sent_vec(sent):
    vector_size = wv.vector_size
    wv_res = np.zeros(vector_size)
    # print(wv_res)
    ctr = 1
    for w in sent:
        if w in wv:
            ctr += 1
            wv_res += wv[w]
    wv_res = wv_res/ctr
    return wv_res

In [17]:
df['word2vec']= df['processed'].apply(sent_vec)

df[['word2vec','processed', 'vector', 'label']].head()

word2vec  \
0  [-0.1852559671773539, 0.11430180537236201, -0....   
1  [-0.19078907463121117, 0.12087538819875776, -0...   
2  [-0.19905917615775603, 0.11765666180346386, -0...   
3  [-0.1562933152721774, 0.08986048544606855, -0....   
4  [-0.11578736018613388, 0.08055306523224044, 0....   

                                           processed  \
0  ethiopian airlines ea flight et3717 was interc...   
1  details it is ethiopian airlines flight smoke ...   
2  i look forward to seeing integrated infrastruc...   
3  jaeyoonie me getting on ethiopian airlines and...   
4  eth552 etavenuea350 941 ethiopian airlines adu...   

                                              vector     label  
0  [-0.02903445, 0.022428248, -0.05338361, 0.0497...  negative  
1  [-0.0039975177, 0.10077321, -0.028292205, 0.06...  negative  
2  [-0.02492736, 0.04924348, -0.014382833, 0.0545...  positive  
3  [0.0296782, 0.117856614, 0.015417021, 0.026076...  negative  
4  [0.03090392, 0.03790238, -0.057798278, 0.00320...   neutral

In [18]:
from sentence_transformers import util
cosine= util.pytorch_cos_sim(df['vector'][1], df['vector'][3])

print(cosine)

tensor([[0.4266]])


In [19]:
df['airline_sentiment']= df['label'].astype('category').cat.codes

df['airline_sentiment'].head()

0    0
1    0
2    2
3    0
4    1
Name: airline_sentiment, dtype: int8

In [44]:
X= df['vector'].tolist()
y= df['airline_sentiment'].tolist()

In [45]:
from imblearn.over_sampling import SMOTE

over= SMOTE()
X, y = over.fit_resample(X, y)

In [46]:
len(y)

6822

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_text, y_train, y_test= train_test_split(X, y, test_size=0.2, stratify=y)

In [48]:
len(X_train)

5457

In [49]:
len(y_train)

5457

In [50]:
from sklearn.ensemble import RandomForestClassifier

rf= RandomForestClassifier()

rf.fit(X_train, y_train)

RandomForestClassifier()

In [51]:
pred= rf.predict(X_text)

In [52]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,pred)
print(matrix)
score=accuracy_score(y_test,pred)
print(score)
report=classification_report(y_test,pred)
print(report)


[[423  23   9]
 [ 30 395  30]
 [ 11  55 389]]
0.8842490842490842
              precision    recall  f1-score   support

           0       0.91      0.93      0.92       455
           1       0.84      0.87      0.85       455
           2       0.91      0.85      0.88       455

    accuracy                           0.88      1365
   macro avg       0.89      0.88      0.88      1365
weighted avg       0.89      0.88      0.88      1365



In [53]:
from sklearn.linear_model import LogisticRegression

lr= LogisticRegression()

lr.fit(X_train, y_train)

predi= lr.predict(X_text)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,predi)
print(matrix)
score=accuracy_score(y_test,predi)
print(score)
report=classification_report(y_test,predi)
print(report)


[[412  29  14]
 [ 33 363  59]
 [ 31  55 369]]
0.8380952380952381
              precision    recall  f1-score   support

           0       0.87      0.91      0.89       455
           1       0.81      0.80      0.80       455
           2       0.83      0.81      0.82       455

    accuracy                           0.84      1365
   macro avg       0.84      0.84      0.84      1365
weighted avg       0.84      0.84      0.84      1365



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [54]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

pred= gnb.predict(X_text)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,pred)
print(matrix)
score=accuracy_score(y_test,pred)
print(score)
report=classification_report(y_test,pred)
print(report)

[[340  56  59]
 [ 37 365  53]
 [ 29  96 330]]
0.7582417582417582
              precision    recall  f1-score   support

           0       0.84      0.75      0.79       455
           1       0.71      0.80      0.75       455
           2       0.75      0.73      0.74       455

    accuracy                           0.76      1365
   macro avg       0.76      0.76      0.76      1365
weighted avg       0.76      0.76      0.76      1365



In [60]:
randomclassifier=RandomForestClassifier(n_estimators=90, criterion='entropy')
randomclassifier.fit(X_train,y_train)

pred= randomclassifier.predict(X_text)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,pred)
print(matrix)
score=accuracy_score(y_test,pred)
print(score)
report=classification_report(y_test,pred)
print(report)

[[428  18   9]
 [ 27 401  27]
 [  9  38 408]]
0.9062271062271062
              precision    recall  f1-score   support

           0       0.92      0.94      0.93       455
           1       0.88      0.88      0.88       455
           2       0.92      0.90      0.91       455

    accuracy                           0.91      1365
   macro avg       0.91      0.91      0.91      1365
weighted avg       0.91      0.91      0.91      1365



In [61]:
from sklearn.tree import DecisionTreeClassifier
dTree_clf = DecisionTreeClassifier()
dTree_clf.fit(X_train,y_train)

pred= dTree_clf.predict(X_text)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,pred)
print(matrix)
score=accuracy_score(y_test,pred)
print(score)
report=classification_report(y_test,pred)
print(report)

[[379  44  32]
 [ 46 324  85]
 [ 23  73 359]]
0.778021978021978
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       455
           1       0.73      0.71      0.72       455
           2       0.75      0.79      0.77       455

    accuracy                           0.78      1365
   macro avg       0.78      0.78      0.78      1365
weighted avg       0.78      0.78      0.78      1365



In [62]:
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [63]:
import numpy as np
x_t= np.array(X_train)
y_t= np.array(y_train)
x= np.array(X_text)
y= np.array(y_test)

In [64]:
import xgboost as xgb

xgb_classifier = xgb.XGBClassifier()

xgb_classifier.fit(x_t,y_t)

predictions = xgb_classifier.predict(x)

matrix=confusion_matrix(y,predictions)
print(matrix)
score=accuracy_score(y_test,predictions)
print(score)
report=classification_report(y_test,predictions)
print(report)

[[415  25  15]
 [ 33 376  46]
 [ 20  49 386]]
0.8622710622710623
              precision    recall  f1-score   support

           0       0.89      0.91      0.90       455
           1       0.84      0.83      0.83       455
           2       0.86      0.85      0.86       455

    accuracy                           0.86      1365
   macro avg       0.86      0.86      0.86      1365
weighted avg       0.86      0.86      0.86      1365



In [34]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000]
}

rfe = RandomForestClassifier()

grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

In [35]:
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy

In [36]:
grid_search.fit(X_train, y_train)
grid_search.best_params_
{'bootstrap': True,
 'max_depth': 80,
 'max_features': 3,
 'min_samples_leaf': 5,
 'min_samples_split': 12,
 'n_estimators': 100}
best_grid = grid_search.best_estimator_
grid_accuracy = evaluate(best_grid, X_text, y_test)

Fitting 3 folds for each of 288 candidates, totalling 864 fits


KeyboardInterrupt: ignored

In [37]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_t, y_t)  
pred= classifier.predict(x)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y,pred)
print(matrix)
score=accuracy_score(y,pred)
print(score)
report=classification_report(y,pred)
print(report)

[[168  25  14]
 [ 25 401  29]
 [ 27  58 139]]
0.7990970654627539
              precision    recall  f1-score   support

           0       0.76      0.81      0.79       207
           1       0.83      0.88      0.85       455
           2       0.76      0.62      0.68       224

    accuracy                           0.80       886
   macro avg       0.79      0.77      0.78       886
weighted avg       0.80      0.80      0.80       886



In [38]:
y= df['airline_sentiment'].tolist()
X= df['word2vec'].tolist()

In [39]:
from imblearn.over_sampling import SMOTE

over= SMOTE()

X, y= over.fit_resample(X,y)

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2)

In [41]:
len(y_train)

5457

In [42]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(X_train, y_train)  

pred= classifier.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,pred)
print(matrix)
score=accuracy_score(y_test,pred)
print(score)
report=classification_report(y_test,pred)
print(report)

[[313  40 102]
 [103 210 142]
 [154  63 238]]
0.5575091575091575
              precision    recall  f1-score   support

           0       0.55      0.69      0.61       455
           1       0.67      0.46      0.55       455
           2       0.49      0.52      0.51       455

    accuracy                           0.56      1365
   macro avg       0.57      0.56      0.56      1365
weighted avg       0.57      0.56      0.56      1365



In [43]:
from sklearn.ensemble import RandomForestClassifier
randomclassifier=RandomForestClassifier(n_estimators=200, criterion='entropy')
randomclassifier.fit(X_train,y_train)

pred= randomclassifier.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

matrix=confusion_matrix(y_test,pred)
print(matrix)
score=accuracy_score(y_test,pred)
print(score)
report=classification_report(y_test,pred)
print(report)

[[402  29  24]
 [ 35 342  78]
 [ 25  47 383]]
0.8256410256410256
              precision    recall  f1-score   support

           0       0.87      0.88      0.88       455
           1       0.82      0.75      0.78       455
           2       0.79      0.84      0.81       455

    accuracy                           0.83      1365
   macro avg       0.83      0.83      0.83      1365
weighted avg       0.83      0.83      0.83      1365

